language: python
python:
- '2.7'
sudo: required
install:
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 6
- node --version
- source scripts/install.sh
script:
- source scripts/test.sh
deploy:
  provider: script
  script: source scripts/deploy.sh
  on:
    branch: develop